import Head from 'next/head';

const Header: React.FC<{ pageTitle?: string }> = ({ pageTitle }) => {
  return (
    <Head>
      <title>{pageTitle ?? 'Chat Application'}</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
};

export default Header;
